general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: WARN

  front_end:
    _type: fastapi

  front_end:
    _type: console

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0

functions: 
  execute_pandas: 
    - _type: execute_pandas
    
workflow:
  _type: react_agent
  tools_names: 
    - execute_pandas
  llm_name: nim_llm
  verbose: true
  retry_parsing_errors: true
  max_retries: 3