general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: DEBUG

  front_end:
    _type: fastapi

  front_end:
    _type: console

  telemetry:
    tracing:
      phoenix:
        _type: phoenix
        endpoint: http://localhost:6006/v1/traces
        project: Experiment4

llms:
  nim_llm:
    _type: nim
    temperature: 0.0 
    model_name : meta/llama-3.1-405b-instruct

functions:
  table_agent: 
    _type: z1structuredToolPandas # no change from previous
    llm: nim_llm
    csv_file: "/workspaces/do_aiq2/_data/retail_customer/Retail_Customer_Cluster_Data.xlsx"
    csv_metafile: "/workspaces/do_aiq2/_data/retail_customer/meta.md"
    description: "Use this tool to get data related to Customer Retails."
  
workflow: 
  _type: react_agent
  tool_names: [table_agent]
  llm_name: nim_llm 
  verbose: true 
  handle_parsing_errors: false 
  max_retries: 0
  system_prompt: |
    Answer the following questions as best you can. You may ask the human to use the following tools:

    {tools}

    Some key things to to take care
    - When asked about your capabilities. Tell from the description of tools available to you.
    - If asked in detail about capabilities then ask the tool what kind of information they can provide in general, irrespective of user query.
    - You must then uses the knowledge from the tool to build [Thought]
    - You must always provide numerical facts along with you opinion whenn responding to end user.

    You may respond in one of two formats.
    Use the following format exactly to ask the human to use a tool:

    Question: the input question you must answer
    Thought: you should always think about what to do based on the tools available; at times its best to ask the tool as is the user query cuz some tools are smart enough
    Action: the action to take, should be one of [{tool_names}]
    Action Input: the input to the action (if there is no required input, include "Action Input: None")  // you can also supply you thoughts to these tools if the tools supports so.
    Observation: wait for the human to respond with the result from the tool, do not assume the response

    ... (this Thought/Action/Action Input/Observation can repeat N times. If you do not need to use a tool, or after asking the human to use any tools and waiting for the human to respond, you might know the final answer.)
    Use the following format once you have the final answer:

    Thought: I now know the final answer
    Final Answer: the final answer to the original input question
    """
    USER_PROMPT = """
    Question: {question}



