general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: WARN

  telemetry:
    logging:
      console:
        _type: console
        level: WARN
    tracing:
      phoenix:
        _type: phoenix
        endpoint: http://localhost:6006/v1/traces
        project: zlanggraph

  front_end:
    _type: fastapi

  front_end:
    _type: console

functions: 
  joke: 
    _type: zjoke 
    description: "Use this tool to tell jokes"

llms:
  nim_llm:
    _type: nim
    model_name : meta/llama-3.1-405b-instruct
    temperature: 0.0 

workflow:
  _type: zlanggraph
  llm: nim_llm
  tool_names: 
    - joke